import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/base.module.scss'
import { GlobalHeader } from '@/components/GlobalHeader'
import { KeyVisual } from '@/components/KeyVisual'
import { CommonButton } from '@/components/common/CommonButton'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalHeader />
      <main className={`${styles.main} ${inter.className}`}>
        <KeyVisual />
        <CommonButton 
          text="Add to Cart"
        />
      </main>
    </>
  )
}
